@startuml ""
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(admin, "Administrador", "Gestiona el catálogo de su tienda de muebles")
Person(user, "Usuario", "Visualiza productos desde la aplicación móvil")

System(system, "Sistema de Catalogación de Muebles", "Permite gestionar y visualizar productos en 3D con RA")

System_Ext(cloudflare, "Cloudflare R2", "Almacenamiento de modelos 3D e imágenes de productos")
System_Ext(firebase, "Firebase Authentication", "Autenticación de usuarios mediante correo")

Rel(admin, system, "Gestiona productos y visualiza estadísticas")
Rel(user, system, "Explora el catálogo de la tienda")

Rel(system, cloudflare, "Guarda y accede a imágenes y modelos 3D", "HTTPS")
Rel(system, firebase, "Autentica a los usuarios", "HTTPS")

@enduml
