@startuml ""
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(admin, "Administrador", "Gestiona el catálogo de su tienda de muebles")
Person(user, "Usuario", "Visualiza productos desde la aplicación móvil")

System_Boundary(system, "Sistema de Catalogación de Muebles") {
    Container(webApp, "Panel de Administración (Web)", "React", "Interfaz para administrar el catálogo y consultar métricas")
    Container(mobileApp, "Aplicación Móvil", "Kotlin", "Interfaz para explorar productos en RA")

    Container(apiGateway, "API Gateway", "Node.js", "Redirige solicitudes a los servicios correspondientes")

    Container(authService, "Servicio de Autenticación", "NestJS", "Gestiona usuarios, roles y tenants")
    ContainerDb(authDb, "Base de Datos de Usuarios", "PostgreSQL", "Almacena usuarios y metadatos de autenticación")

    Container(productService, "Servicio de Productos", "Java Spring Boot", "Lógica de negocio para gestión de productos")
    Container(mediaService, "Servicio de Medios", "Node.js", "Gestión de imágenes y modelos 3D")
    Container(modelingService, "Servicio de Modelado 3D", "Python + COLMAP", "Genera modelos 3D a partir de imágenes (fotogrametría)")

    ContainerDb(productsDb, "Base de Datos de Productos", "PostgreSQL", "Almacena información de productos y medios en esquema compartido")
}

System_Ext(cloudStorage, "Almacenamiento en la Nube", "Cloudflare R2", "Guarda imágenes y modelos 3D")
System_Ext(firebaseAuth, "Firebase Authentication", "Proporciona autenticación con correo y proveedores externos")
Lay_L(authService, firebaseAuth)


Rel(admin, webApp, "Utiliza")
Rel(user, mobileApp, "Utiliza")

Rel(webApp, apiGateway, "Envía solicitudes")
Rel(mobileApp, apiGateway, "Envía solicitudes")

Rel(apiGateway, authService, "Redirige solicitudes")
Rel(apiGateway, productService, "Redirige solicitudes")
Rel(apiGateway, mediaService, "Redirige solicitudes")
Rel(apiGateway, modelingService, "Redirige solicitudes")

Rel(authService, authDb, "Lee y escribe")
Rel(authService, firebaseAuth, "Verifica tokens y claims personalizados", "HTTPS")

Rel(productService, productsDb, "Lee y escribe")
Rel(mediaService, cloudStorage, "Sube y descarga archivos", "HTTPS")
Rel(modelingService, cloudStorage, "Guarda modelos generados", "HTTPS")

@enduml
